name: groscross
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: "none" # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 2.0.1+71

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  adaptive_theme: 3.3.0
  animated_bottom_navigation_bar: ^1.2.0
  awesome_notifications: 0.7.4+1
  banner_carousel: ^1.2.1
  basic_utils: ^3.9.0
  cached_network_image: ^3.2.1
  carousel_slider: ^4.1.1
  chewie: ^1.5.0
  cloud_firestore: 4.8.1
  contained_tab_bar_view: ^0.8.0
  cool_alert: ^1.1.0
  country_picker: 2.0.20
  cupertino_icons: ^1.0.5
  currency_formatter: ^2.0.1
  custom_clippers: ^2.0.0
  custom_faqs:
    git:
      url: https://github.com/ambrosethebuild/custom_faqs
      ref: main
  custom_sliding_segmented_control: 1.7.5
  dartx: ^1.1.0
  dio: ^4.0.6
  dio_http_cache_lts: ^0.4.0
  dotted_border: ^2.0.0+2
  dotted_line: ^3.1.0
  double_back_to_close: ^2.0.0
  dynamic_height_grid_view: ^0.0.3
  equatable: ^2.0.3
  expand_widget: ^2.1.0
  firebase_auth: ^4.6.3
  firebase_core: ^2.14.0
  firebase_crashlytics: ^3.3.3
  firebase_dynamic_links: ^5.3.3
  firebase_messaging: ^14.6.3
  firestore_chat: ^0.1.1
  fl_location: ^1.2.2
  flag: ^5.0.1
  flutter:
    sdk: flutter
  flutter_facebook_auth: ^4.4.0+1
  flutter_form_builder: 9.0.0
  flutter_icons:
    git:
      url: https://github.com/imclerran/flutter-icons.git
      ref: dart-3
  flutter_image_compress: ^1.1.3
  flutter_inappwebview: 5.7.2+3
  flutter_localizations:
    sdk: flutter
  flutter_overboard: ^3.1.1
  flutter_polyline_points: ^1.0.0
  flutter_rating_bar: ^4.0.1
  flutter_signin_button: ^2.0.0
  flutter_sim_country_code: ^0.1.2
  flutter_staggered_animations: ^1.0.0
  flutter_svg: ^1.1.1+1
  flutter_typeahead: ^4.3.7
  fluttercontactpicker: ^4.7.0
  fluttertoast: ^8.0.9
  geolocator: ^9.0.2
  glass: ^1.0.1+1
  glass_kit: ^2.0.1
  google_fonts: 5.1.0
  google_maps_flutter: ^2.3.1
  google_maps_place_picker_mb: ^3.0.2
  google_nav_bar: ^5.0.6
  google_places_flutter: ^2.0.5
  google_sign_in: ^5.3.3
  group_radio_button: 1.2.0
  http: ^1.0.0
  image_picker: 1.0.0
  in_app_review: ^2.0.4
  inspection: ^0.0.13
  jiffy: ^5.0.0
  keyboard_dismisser: ^3.0.0
  line_icons: ^2.0.1
  localize_and_translate: ^4.1.1
  location: ^4.4.0
  map_launcher: ^2.2.3
  maps_toolkit: ^2.0.1
  masonry_grid: ^1.0.0
  measure_size: ^3.0.1
  package_info_plus: ^4.0.2
  pin_code_fields: ^7.4.0
  pinch_zoom: ^1.0.0
  pretty_dio_logger: ^1.2.0-beta-1
  pull_to_refresh_flutter3: ^2.0.1
  qr_code_scanner: ^1.0.1
  qr_flutter: ^4.0.0
  rx_shared_preferences: ^3.0.0
  rxdart: ^0.27.7
  share: ^2.0.4
  shared_preferences: ^2.0.15
  sign_in_with_apple: ^4.0.0
  singleton: ^0.0.3-nullsafety
  slide_countdown: ^0.2.8
  sliding_up_panel: ^2.0.0+1
  smooth_page_indicator: ^1.0.0+2
  spider: ^2.1.0
  stacked: 3.4.0
  sticky_headers: ^0.3.0+2
  supercharged: ^2.1.1
  synchronized: ^3.0.1
  timelines: ^0.1.0
  upgrader: 7.1.0
  url_launcher: ^6.1.4
  velocity_x: 4.1.0
  what3words: ^3.1.0

dependency_overrides:
  intl: ^0.18.1
  http: ^0.13.0
  win32: ^5.0.0

dev_dependencies:
  flutter_application_id: ^2.0.0-dev
  flutter_launcher_icons: ^0.9.3
  flutter_native_splash: ^2.2.4
  flutter_test:
    sdk: flutter
  translator: ^0.1.7

flutter_icons:
  android: "launcher_icon"
  ios: true
  remove_alpha_ios: true
  image_path: "assets/images/app_icon.png"
  adaptive_icon_foreground: "assets/images/app_icon.png"
  adaptive_icon_background: "#5e17eb"

flutter:
  uses-material-design: true
  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/
    - assets/images/icons/
    - assets/json/
    - assets/lang/
    - assets/
